# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: b9e7c5ecff727355ccc05ed90e0270c42b534415d4accc405b8ee634b9411cdfb49b8176afa70d89e878f1d7de0324845c05511479c10a3ba068e07f7e0941b0

test:
  secret_key_base: fbdee3a1904414ab1e3e8969ac15f4ea656393d0ee6e188419092b29702e0403d66dd73d0a586691257db39fd2d52c817701efee20b661e4078928f6173332ab

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
